### ISSUE TITLE
No Styling?

### ISSUE THREAD

**Issue by phil-kt** [makotot/react-reading-progress#1]
Hi, thanks for making this project!

I just tried installing it and noticed that by default there is not styling attached to the Component? Is this intentional? I really think it'd be beneficial to at least have the styling of the demo as a starting point.

**Comment by makotot** [comment]
@LinkCable Yeah, this is intentional. Because there are various ways of putting styles according to people who use it, I think that styling is unnecessary.

**Comment by phil-kt** [comment]
Hmm, then the demo page feels little deceiving doesn't it? Usually React Components like this include their styling so that devs can plug and play. 

Maybe add an optional style prop or something so it can be overridden and default to your example? Especially since `progress` and progress styling is still very much in its infancy as far the standard goes, your example provides a good jumping off point?

**Comment by makotot** [comment]
> Hmm, then the demo page feels little deceiving doesn't it? Usually React Components like this include their styling so that devs can plug and play.

possibly.
Including default theme & adding a prop to add custom style may be great. I will take time this weekend to check this more.

**Comment by phil-kt** [comment]
One more thing 😅

Have you thought about using componentWillReceiveProps to update the length of the progress that you've gone through? In my case I have collapsable sections on my page, that throw off the estimate as the length doesn't update is the content in the body changes.

**Comment by makotot** [comment]
Added default style in v0.3.0.

> Have you thought about using componentWillReceiveProps to update the length of the progress that you've gone through? In my case I have collapsable sections on my page, that throw off the estimate as the length doesn't update is the content in the body changes.

Ok, thanks for reporting :) I'll check it out later.
